import "./globals.css";

import FooterBar from "@/components/FooterBar";
import HeaderBar from "@/components/HeaderBar";
import { Inter } from "next/font/google";
const inter = Inter({
  weight: ["100", "200", "300", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}` + " overflow-x-hidden text-slate-600"}
      >
        <HeaderBar />
        {children}
        <FooterBar />
      </body>
    </html>
  );
}
